class_name LeagueCatalog
extends RefCounted

const SOURCE_FICTIONAL := "fictional"
const SOURCE_NFLVERSE_PREVIEW := "nflverse_2026_preview"
const SOURCE_NFLVERSE_FULL := "nflverse_2026_full"
const NFLVERSE_FULL_PATH := "res://data/leagues/nflverse_2026_full.json"


static func source_descriptors() -> Array[Dictionary]:
	return [
		{
			"id": SOURCE_NFLVERSE_FULL,
			"label": "NFLVERSE + MADDEN 26",
			"title": "Hybrid 32-team player database",
			"description": "All 32 clubs and the 2026 schedule from nflverse, joined to 2,035 Madden-rated players, complete attributes, contracts, and an expanded free-agent market.",
			"badge": "HYBRID DATA",
		},
	]


static func create_bundle(source_id: String = SOURCE_NFLVERSE_FULL) -> Dictionary:
	if source_id in [SOURCE_NFLVERSE_FULL, SOURCE_NFLVERSE_PREVIEW]:
		return LeagueDataPackProvider.load_bundle(NFLVERSE_FULL_PATH)
	return {
		"teams": SampleLeague.create_teams(),
		"free_agents": SampleLeague.create_free_agents(),
		"schedule": [],
		"league_format": LeagueFormatData.legacy_eight(),
		"source": {
			"id": SOURCE_FICTIONAL,
			"label": "ORIGINAL LEAGUE",
			"league_name": "Gridiron League",
			"snapshot_date": "",
			"attribution": "Original fictional league content generated by Gridiron Manager.",
		},
	}
