class_name LeagueCatalog
extends RefCounted

const SOURCE_FICTIONAL := "fictional"
const SOURCE_NFLVERSE_PREVIEW := "nflverse_2026_preview"
const NFLVERSE_PREVIEW_PATH := "res://data/leagues/nflverse_2026_preview.json"


static func source_descriptors() -> Array[Dictionary]:
	return [
		{
			"id": SOURCE_FICTIONAL,
			"label": "ORIGINAL LEAGUE",
			"title": "Gridiron League",
			"description": "Eight original clubs with fully generated players and long-term careers.",
			"badge": "FICTIONAL",
		},
		{
			"id": SOURCE_NFLVERSE_PREVIEW,
			"label": "NFLVERSE PREVIEW",
			"title": "2026 real-data preview",
			"description": "Eight representative clubs built from nflverse rosters, recent stats, and contract data.",
			"badge": "REAL DATA",
		},
	]


static func create_bundle(source_id: String = SOURCE_FICTIONAL) -> Dictionary:
	if source_id == SOURCE_NFLVERSE_PREVIEW:
		return LeagueDataPackProvider.load_bundle(NFLVERSE_PREVIEW_PATH)
	return {
		"teams": SampleLeague.create_teams(),
		"free_agents": SampleLeague.create_free_agents(),
		"source": {
			"id": SOURCE_FICTIONAL,
			"label": "ORIGINAL LEAGUE",
			"league_name": "Gridiron League",
			"snapshot_date": "",
			"attribution": "Original fictional league content generated by Gridiron Manager.",
		},
	}
